services:
  smartcanopy-api:
    build: .
    container_name: smartcanopy-api
    restart: always
    env_file: .env
    ports:
      - '26925:26925'
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
