services:
  smartcanopy-api:
    build: .
    container_name: smartcanopy-api
    restart: always
    ports:
      - '26925:26925'
    networks:
      - cf-net

networks:
  cf-net:
    external: true
